on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0
 
    services:
      pgsql:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: postgres

        volumes:
        - './pgdata/docker-entrypoint-initdb.d'
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v3

  
    - name: Install composer dependencies
      run: |
        make install
  
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        make key
        make migrate
  
    - name: Run Testsuite
      run: make ci-test